version: "3.9"
services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
     - 9090:9090

  grafana:
    image: grafana/grafana
    ports:
     - "80:3000"
    volumes:
      - ./grafana/:/etc/grafana/provisioning/
    depends_on:
      - prometheus

  # pull-push-app:

